[package]
name = "loxrs_vm"
version = "0.1.0"
authors = ["toyboot4e <toyboot4e@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
anyhow = "1.0.31"
thiserror = "1.0.19"

env_logger = "0.8.1"

[[bin]]
name = "loxrs"
path = "bin/main.rs"
